name: CI / Verify Assets

on:
  push:
    branches: [ "master", "*" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - name: Install Neofetch
        run: |
          sudo apt install neofetch
          neofetch
