name: Mark Stale Issues and PRs

on:
  schedule:
  - cron: '35 4 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
    - uses: actions/stale@v5
      with:
        repo-token: ${{ secrets.GH_TOKEN }}
        stale-issue-message: 'Reported - Stale issue'
        stale-pr-message: 'Reported - Stale pull request'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
